language: scala
jdk:
  - openjdk8
script: sbt test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/72d2a40c7c3ae2988d66
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
sudo: false
services:
  - memcached
